### ISSUE TITLE
64 bit problems

### ISSUE THREAD

**Issue by hafedh-trimeche** [NGLN/AwImageGrid#1]
Hi,

Please note:
`TImageGridItemList = array[0..MaxListSize div 2] of TImageGridItem;`
generates [dcc64 Error] AwImageGrid.pas(31): E2100 Data type too large: exceeds 2 GB 

and 
`[dcc64 Error] AwImageGrid.pas(638): E2089 Invalid typecast`
for all items.

```
procedure TImageGridItems.ExchangeItems(Index1, Index2: Integer);
var
  Temp: Integer;
  Item1: PImageGridItem;
  Item2: PImageGridItem;
begin
  Item1 := @FList^[Index1];
  Item2 := @FList^[Index2];
  Temp := Integer(Item1^.FFileName);
  Integer(Item1^.FFileName) := Integer(Item2^.FFileName);
  Integer(Item2^.FFileName) := Temp;
  Temp := Integer(Item1^.FObject);
  Integer(Item1^.FObject) := Integer(Item2^.FObject);
  Integer(Item2^.FObject) := Temp;
  Temp := Integer(Item1^.FThumb);
  Integer(Item1^.FThumb) := Integer(Item2^.FThumb);
  Integer(Item2^.FThumb) := Temp;
end;

```

**Comment by NGLN** [comment]
Hi,

Thanks for your reply.

I moved the code from D7 to 10.3:
- Added 64-bit compatibility by copying the changes in TStringList implementation
- Removed/changed deprecated code

I wish you success and lots of fun with the component.
